version: '2'

services:
    morpionappli:
      image: morpion
      container_name: morpion
      hostname: morpion
      expose:
        - "9100"
      ports:
        - "80:80"
        - "2222:22" # ssh
    #  entrypoint:
      volumes:
        - /home/projects/morpion:/home/morpion
        - /home/projects:/home/projects
      tty: true
      dns:
        - 8.8.8.8
        - 8.8.4.4
      links:
        - morpionmysql
      environment:
        PHP_XDEBUG_ENABLED: 1 # Set 1 to enable.
        XDEBUG_CONFIG: remote_host=192.168.254.254
    morpionmysql:
        image: mysql/mysql-server
        container_name: morpionmysql
#       volumes:
#         - /var/lib/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: mypass
        ports:
            - "3306:3306"
